#!/bin/sh

# This worked with default Slackware consolekit:
# pkexec "/usr/sbin/gtkkeyboardsetup" "$@"

# This is working with ConsoleKit2: 
pkexec env "DISPLAY=$DISPLAY" "XAUTHORITY=$XAUTHORITY" "/usr/sbin/gtkkeyboardsetup" "$@"