#!/bin/sh
git clone https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git
cd efitools/
export VERSION=$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")
cd ..
mv efitools/ efitools-$VERSION/
rm -rf efitools-$VERSION/{.git*,.travis*}
tar jcvf efitools-$VERSION.tar.bz2 efitools-$VERSION
rm -rf efitools-$VERSION/
echo ""
echo "Done cloning efitools. Tarball is ready!"
sleep 2
exit