#!/bin/sh

ver=1.2

mkdir opencl-headers-1.2

cd opencl-headers-1.2/

wget \
 http://www.khronos.org/registry/cl/api/${ver}/cl_ext.h \
 http://www.khronos.org/registry/cl/api/${ver}/cl_gl_ext.h \
 http://www.khronos.org/registry/cl/api/${ver}/cl_gl.h \
 http://www.khronos.org/registry/cl/api/${ver}/cl.h \
 http://www.khronos.org/registry/cl/api/${ver}/cl.hpp \
 http://www.khronos.org/registry/cl/api/${ver}/cl_platform.h \
 http://www.khronos.org/registry/cl/api/${ver}/opencl.h

cd ..

tar jcvf opencl-headers-1.2.tar.bz2 opencl-headers-1.2/
